name: BlazeSpawnerLock
version: 1.7.1
main: org.frh.blazespawnerlock.BlazeSpawnerLock
api-version: '1.21'
author: airtagdev
description: Prevents blaze spawners from being broken or exploded

permissions:
  blazespawnerlock.bypass:
    description: Allows breaking blaze spawners
    default: op

  blazespawnerlock.reload:
    description: Allows reloading BlazeSpawnerLock config
    default: op

commands:
  blazespawnerlock:
    description: Main BlazeSpawnerLock command
    usage: /<command> reload | update
    permission: blazespawnerlock.reload
    aliases: [bsl]
